FROM  python

WORKDIR /backend-flask

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .



EXPOSE ${PORT}

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]